"""add levels and user_progress tables

Revision ID: fd952accfe63
Revises: f0b6e7a0ac4a
Create Date: 2026-09-04 01:41:22.238260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd952accfe63'
down_revision: Union[str, Sequence[str], None] = 'f0b6e7a0ac4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
