"""enforce unique practice lesson association

Revision ID: 0d419299f4dc
Revises: 57bc72bc69c5
Create Date: 2026-09-28 17:17:35.151712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d419299f4dc'
down_revision: Union[str, Sequence[str], None] = '57bc72bc69c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_lesson_practices_practice', 'lesson_practices', ['practice_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_lesson_practices_practice', 'lesson_practices', type_='unique')
    # ### end Alembic commands ###
