"""allow nullable sandbox network configuration

Revision ID: 49a274e32ca3
Revises: 54aeb75dd20e
Create Date: 2026-09-29 00:30:59.582713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a274e32ca3'
down_revision: Union[str, Sequence[str], None] = '54aeb75dd20e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sandbox_environment_networks', 'subnet',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('sandbox_environment_networks', 'gateway',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sandbox_environment_networks', 'gateway',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('sandbox_environment_networks', 'subnet',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
