"""create practice activities

Revision ID: 4e60f7f80278
Revises: e9c1fe1bfe90
Create Date: 2026-09-28 16:57:00.593428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e60f7f80278'
down_revision: Union[str, Sequence[str], None] = 'e9c1fe1bfe90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_activities',
    sa.Column('practice_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('TEXT_QUESTION', 'PRACTICAL_TASK', 'GUIDED_CTF', name='practice_activity_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('evaluation_type', sa.Enum('MULTIPLE_CHOICE', 'TEXT_EXACT', 'TEXT_NORMALIZED', 'TEXT_CASE_INSENSITIVE', 'COMMAND_RESULT', 'OUTPUT_EXTRACTION', 'FLAG_SUBMISSION', name='practice_evaluation_type'), nullable=False),
    sa.Column('environment_requirement_id', sa.Uuid(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('guidance_policy', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practice_id', 'position', name='uq_practice_activities_practice_position')
    )
    op.create_index(op.f('ix_practice_activities_practice_id'), 'practice_activities', ['practice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_activities_practice_id'), table_name='practice_activities')
    op.drop_table('practice_activities')
    # ### end Alembic commands ###
