"""create sandbox environment models

Revision ID: 54aeb75dd20e
Revises: ceac4b897527
Create Date: 2026-09-28 21:08:37.155995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54aeb75dd20e'
down_revision: Union[str, Sequence[str], None] = 'ceac4b897527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sandbox_environments',
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Enum('REQUESTED', 'PROVISIONING', 'READY', 'ACTIVE', 'RESETTING', 'STOPPED', 'TERMINATING', 'DESTROYED', 'FAILED', name='sandbox_environment_state', native_enum=False), server_default='requested', nullable=False),
    sa.Column('state_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_environments_activity_id'), 'sandbox_environments', ['activity_id'], unique=False)
    op.create_index(op.f('ix_sandbox_environments_learner_id'), 'sandbox_environments', ['learner_id'], unique=False)
    op.create_table('sandbox_environment_machines',
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ATTACK', 'TARGET', 'GATEWAY', name='sandbox_machine_role', native_enum=False), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('runtime_machine_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['sandbox_environments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_environment_machines_environment_id'), 'sandbox_environment_machines', ['environment_id'], unique=False)
    op.create_table('sandbox_environment_networks',
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subnet', sa.String(length=64), nullable=False),
    sa.Column('gateway', sa.String(length=64), nullable=False),
    sa.Column('runtime_network_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['sandbox_environments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_environment_networks_environment_id'), 'sandbox_environment_networks', ['environment_id'], unique=False)
    op.create_table('sandbox_machine_interfaces',
    sa.Column('machine_id', sa.Uuid(), nullable=False),
    sa.Column('network_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['sandbox_environment_machines.id'], ),
    sa.ForeignKeyConstraint(['network_id'], ['sandbox_environment_networks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'name', name='uq_sandbox_machine_interface_name'),
    sa.UniqueConstraint('machine_id', 'network_id', name='uq_sandbox_machine_network')
    )
    op.create_index(op.f('ix_sandbox_machine_interfaces_machine_id'), 'sandbox_machine_interfaces', ['machine_id'], unique=False)
    op.create_index(op.f('ix_sandbox_machine_interfaces_network_id'), 'sandbox_machine_interfaces', ['network_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sandbox_machine_interfaces_network_id'), table_name='sandbox_machine_interfaces')
    op.drop_index(op.f('ix_sandbox_machine_interfaces_machine_id'), table_name='sandbox_machine_interfaces')
    op.drop_table('sandbox_machine_interfaces')
    op.drop_index(op.f('ix_sandbox_environment_networks_environment_id'), table_name='sandbox_environment_networks')
    op.drop_table('sandbox_environment_networks')
    op.drop_index(op.f('ix_sandbox_environment_machines_environment_id'), table_name='sandbox_environment_machines')
    op.drop_table('sandbox_environment_machines')
    op.drop_index(op.f('ix_sandbox_environments_learner_id'), table_name='sandbox_environments')
    op.drop_index(op.f('ix_sandbox_environments_activity_id'), table_name='sandbox_environments')
    op.drop_table('sandbox_environments')
    # ### end Alembic commands ###
