"""create practice attempts

Revision ID: 57bc72bc69c5
Revises: 8eae1cead72f
Create Date: 2026-09-28 17:05:11.142571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57bc72bc69c5'
down_revision: Union[str, Sequence[str], None] = '8eae1cead72f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_attempts',
    sa.Column('practice_activity_id', sa.Uuid(), nullable=False),
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('submission_ref', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_no > 0', name='ck_practice_attempts_attempt_no_positive'),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practice_activity_id'], ['practice_activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practice_activity_id', 'learner_id', 'attempt_no', name='uq_practice_attempts_activity_learner_attempt')
    )
    op.create_index(op.f('ix_practice_attempts_learner_id'), 'practice_attempts', ['learner_id'], unique=False)
    op.create_index(op.f('ix_practice_attempts_practice_activity_id'), 'practice_attempts', ['practice_activity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_attempts_practice_activity_id'), table_name='practice_attempts')
    op.drop_index(op.f('ix_practice_attempts_learner_id'), table_name='practice_attempts')
    op.drop_table('practice_attempts')
    # ### end Alembic commands ###
