"""create lesson practices

Revision ID: 8eae1cead72f
Revises: 4e60f7f80278
Create Date: 2026-09-28 17:00:06.224396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eae1cead72f'
down_revision: Union[str, Sequence[str], None] = '4e60f7f80278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_practices',
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('practice_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_lesson_practices_position_nonnegative'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'position', name='uq_lesson_practices_lesson_position'),
    sa.UniqueConstraint('lesson_id', 'practice_id', name='uq_lesson_practices_lesson_practice')
    )
    op.create_index(op.f('ix_lesson_practices_lesson_id'), 'lesson_practices', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_practices_practice_id'), 'lesson_practices', ['practice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_practices_practice_id'), table_name='lesson_practices')
    op.drop_index(op.f('ix_lesson_practices_lesson_id'), table_name='lesson_practices')
    op.drop_table('lesson_practices')
    # ### end Alembic commands ###
