"""create lesson content blocks

Revision ID: 9cf7ed15f1e9
Revises: b02facb1fedb
Create Date: 2026-09-28 16:45:22.742078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf7ed15f1e9'
down_revision: Union[str, Sequence[str], None] = 'b02facb1fedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_content_blocks',
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.Enum('TEXT', 'HEADING', 'CODE', 'IMAGE', 'CALLOUT', 'LIST', 'TABLE', 'TERMINAL_OUTPUT', name='lesson_content_block_type'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'position', name='uq_lesson_content_blocks_lesson_position')
    )
    op.create_index(op.f('ix_lesson_content_blocks_lesson_id'), 'lesson_content_blocks', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_content_blocks_lesson_id'), table_name='lesson_content_blocks')
    op.drop_table('lesson_content_blocks')
    # ### end Alembic commands ###
