"""create lessons

Revision ID: b02facb1fedb
Revises: d5e24aa6b37f
Create Date: 2026-09-28 16:40:25.260641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02facb1fedb'
down_revision: Union[str, Sequence[str], None] = 'd5e24aa6b37f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='lesson_status'), nullable=False),
    sa.Column('access_override', sa.Enum('FREE', 'PRO', name='lesson_access_override'), nullable=True),
    sa.Column('completion_rule', sa.Enum('REQUIRED_PRACTICE', name='lesson_completion_rule'), nullable=False),
    sa.Column('environment_requirement_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_lessons_position_nonnegative'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'position', name='uq_lessons_room_position'),
    sa.UniqueConstraint('room_id', 'slug', name='uq_lessons_room_slug')
    )
    op.create_index(op.f('ix_lessons_room_id'), 'lessons', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_room_id'), table_name='lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###
