"""create rooms

Revision ID: d5e24aa6b37f
Revises: e179aa145d11
Create Date: 2026-09-28 16:35:18.858304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e24aa6b37f'
down_revision: Union[str, Sequence[str], None] = 'e179aa145d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('module_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='room_status'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.Enum('FREE', 'PRO', name='room_access_level'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_rooms_position_nonnegative'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'position', name='uq_rooms_module_position'),
    sa.UniqueConstraint('module_id', 'slug', name='uq_rooms_module_slug')
    )
    op.create_index(op.f('ix_rooms_module_id'), 'rooms', ['module_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_module_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
