"""add machine lifecycle routes and services

Revision ID: e3759a74118e
Revises: f3c2a91b7d55
Create Date: 2026-10-07 14:04:04.569820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e3759a74118e'
down_revision: Union[str, Sequence[str], None] = 'f3c2a91b7d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sandbox_machine_routes',
    sa.Column('machine_id', sa.Uuid(), nullable=False),
    sa.Column('network_id', sa.Uuid(), nullable=True),
    sa.Column('destination', sa.String(length=64), nullable=False),
    sa.Column('gateway', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['sandbox_environment_machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['network_id'], ['sandbox_environment_networks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'destination', name='uq_sandbox_machine_route_destination')
    )
    op.create_index(op.f('ix_sandbox_machine_routes_machine_id'), 'sandbox_machine_routes', ['machine_id'], unique=False)
    op.create_table('sandbox_machine_services',
    sa.Column('machine_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('protocol', sa.String(length=10), server_default='tcp', nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['sandbox_environment_machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'protocol', 'port', name='uq_sandbox_machine_service_port')
    )
    op.create_index(op.f('ix_sandbox_machine_services_machine_id'), 'sandbox_machine_services', ['machine_id'], unique=False)
    op.add_column('sandbox_environment_machines', sa.Column('hostname', sa.String(length=63), nullable=True))
    op.add_column('sandbox_environment_machines', sa.Column('state', sa.Enum('CREATING', 'CREATED', 'STARTING', 'RUNNING', 'READY', 'STOPPING', 'STOPPED', 'RESETTING', 'FAILED', 'DESTROYED', name='sandbox_machine_state', native_enum=False), server_default='creating', nullable=False))
    op.add_column('sandbox_environments', sa.Column('failure_reason', sa.String(length=1000), nullable=True))

    # Backfill lifecycle state for machines that already exist: machines of
    # environments that were validated as running are READY, stopped
    # environments are STOPPED, terminated ones DESTROYED.
    op.execute("""
        UPDATE sandbox_environment_machines AS m
        SET state = CASE
            WHEN e.state IN ('ready', 'active') THEN 'ready'
            WHEN e.state = 'stopped' THEN 'stopped'
            WHEN e.state IN ('destroyed', 'terminating') THEN 'destroyed'
            WHEN e.state = 'failed' THEN 'failed'
            ELSE 'creating'
        END
        FROM sandbox_environments AS e
        WHERE m.environment_id = e.id
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sandbox_environments', 'failure_reason')
    op.drop_column('sandbox_environment_machines', 'state')
    op.drop_column('sandbox_environment_machines', 'hostname')
    op.drop_index(op.f('ix_sandbox_machine_services_machine_id'), table_name='sandbox_machine_services')
    op.drop_table('sandbox_machine_services')
    op.drop_index(op.f('ix_sandbox_machine_routes_machine_id'), table_name='sandbox_machine_routes')
    op.drop_table('sandbox_machine_routes')
    # ### end Alembic commands ###
