"""create practices

Revision ID: e9c1fe1bfe90
Revises: 9cf7ed15f1e9
Create Date: 2026-09-28 16:52:22.169970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c1fe1bfe90'
down_revision: Union[str, Sequence[str], None] = '9cf7ed15f1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practices',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='practice_status'), nullable=False),
    sa.Column('activity_mode', sa.Enum('TEXT', 'PRACTICAL', 'GUIDED_CTF', name='practice_activity_mode'), nullable=False),
    sa.Column('environment_requirement_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practices')
    # ### end Alembic commands ###
